version: '3.1'

services:
  gateway:
    container_name: gateway
    build: .
    restart: always
    ports:
      - 80:8080
    networks:
      - n1

  service-one:
    container_name: service-one
    build:
      context: ../service1
    restart: always
    volumes: 
      - ../service1:/usr/src/app
    networks:
      - n1

  service-two:
    container_name: service-two
    build:
      context: ../service2
    restart: always
    volumes: 
      - ../service2:/usr/src/app
    networks:
      - n1

networks:
  n1:
    external: true